# Generated by Django 2.2.6 on 2019-10-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20191014_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[('36', 36), ('38', 38), ('40', 40), ('42', 42), ('44', 44), ('46', 46), ('48', 48)], default=40),
            preserve_default=False,
        ),
    ]
